name: Bubilet Bilet Kontrol

on:
  schedule:
    # GitHub Actions cron en düşük 5 dakikayı destekler. 2 yazılsa bile ortalama 5 dakikada bir çalıştırır.
    - cron: '*/2 * * * *'
  workflow_dispatch: # Butonla manuel çalıştırmak için

jobs:
  check-tickets:
    runs-on: ubuntu-latest

    steps:
      - name: Repodan Kodu Al
        uses: actions/checkout@v4

      - name: Node.js Kurulumu
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Kütüphaneleri Yükle
        run: |
          npm install
          npx playwright install chromium --with-deps

      - name: Scripti Çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node index.js
